export const DECK_THEMES: Record<string, {
  primaryColor: string;
  accentColor: string;
  font: string;
  text: string;
  tagline: string;
  description: string;
  borderRadius: string;
  shadow: string;
  titlePlacement: 'left' | 'center';
  padding: string;
  headerSize: string;
  contentSize: string;
  headerWeight: string;
  backgroundGradient: string;
  borderColor: string;
  templateId: string;
}> = {
  'Silicon Valley VC': {
    primaryColor: '#0a101d',
    accentColor: '#5DA9FF',
    font: '"Space Grotesk", "Inter", sans-serif',
    text: '#E8EDF5',
    tagline: 'HERO-CENTRIC HIGH IMPACT SPEED',
    description: 'Silicon Valley template — massive headlines, minimal text, aggressive traction',
    borderRadius: '16px',
    shadow: '0 8px 32px rgba(93,169,255,0.15)',
    titlePlacement: 'left',
    padding: '3.5rem',
    headerSize: '3.4rem',
    contentSize: '1.25rem',
    headerWeight: '900',
    backgroundGradient: 'radial-gradient(circle at top right, #14203e, #0a101d)',
    borderColor: '#1e293b',
    templateId: 'sv_vc',
  },
  'Startup Minimal': {
    primaryColor: '#FFFFFF',
    accentColor: '#171717',
    font: '"Inter", sans-serif',
    text: '#262626',
    tagline: 'DIRECT FOUNDER CLARITY NO FILLER',
    description: 'No-nonsense layout standardising key objectives and fast investor metrics',
    borderRadius: '0px',
    shadow: 'none',
    titlePlacement: 'left',
    padding: '3.5rem',
    headerSize: '2.5rem',
    contentSize: '1.1rem',
    headerWeight: '800',
    backgroundGradient: 'none',
    borderColor: '#171717',
    templateId: 'startup_minimal',
  },
  'Corporate Executive': {
    primaryColor: '#F7F8FA',
    accentColor: '#1E3A8A',
    font: '"Georgia", serif',
    text: '#1F2937',
    tagline: 'EXECUTIVE AUTHORITY BOARD CONTEXT',
    description: 'High-calibre boardroom consulting format — strategy layouts and regulatory charts',
    borderRadius: '0px',
    shadow: 'none',
    titlePlacement: 'left',
    padding: '4.5rem',
    headerSize: '2.6rem',
    contentSize: '1.18rem',
    headerWeight: '800',
    backgroundGradient: 'none',
    borderColor: '#334155',
    templateId: 'corporate_executive',
  },
  'Fintech Modern': {
    primaryColor: '#0B1120',
    accentColor: '#22D3EE',
    font: '"Outfit", sans-serif',
    text: '#E2E8F0',
    tagline: 'PREMIUM CAPITAL ESCROW BLUEPRINT',
    description: 'Premium liquid-banking layout built around split revenue models',
    borderRadius: '12px',
    shadow: '0 10px 30px rgba(34,211,238,0.1)',
    titlePlacement: 'left',
    padding: '3.6rem',
    headerSize: '2.8rem',
    contentSize: '1.15rem',
    headerWeight: '850',
    backgroundGradient: 'radial-gradient(ellipse at bottom, #111d33, #0B1120)',
    borderColor: '#334155',
    templateId: 'fintech_modern',
  },
  'Healthcare Innovation': {
    primaryColor: '#F4FBF9',
    accentColor: '#0D9488',
    font: '"Plus Jakarta Sans", sans-serif',
    text: '#134E4A',
    tagline: 'CLINICAL RIGOR DISPATCH TIMELINE',
    description: 'Trust-first clinical presentation — trials, medical diagrams, patient care',
    borderRadius: '20px',
    shadow: '0 6px 24px rgba(13,148,136,0.12)',
    titlePlacement: 'center',
    padding: '3.8rem',
    headerSize: '2.7rem',
    contentSize: '1.12rem',
    headerWeight: '700',
    backgroundGradient: 'linear-gradient(135deg, #F4FBF9 0%, #e0f5f0 100%)',
    borderColor: '#1e293b',
    templateId: 'healthcare_innovation',
  },
  'Cybersecurity Command': {
    primaryColor: '#03070C',
    accentColor: '#10B981',
    font: '"JetBrains Mono", monospace',
    text: '#94A3B8',
    tagline: 'INFRASTRUCTURE SECURE HIGH RESOLUTION',
    description: 'Dark tactical military-grade design — deep compliance, edge-proxy flowcharts',
    borderRadius: '8px',
    shadow: '0 4px 24px rgba(16,185,129,0.15)',
    titlePlacement: 'left',
    padding: '3.2rem',
    headerSize: '2.3rem',
    contentSize: '1.1rem',
    headerWeight: '800',
    backgroundGradient: 'linear-gradient(180deg, #03070C 0%, #101e30 100%)',
    borderColor: '#1f2937',
    templateId: 'cybersecurity_command',
  },
  'Luxury Investor': {
    primaryColor: '#111111',
    accentColor: '#C5A059',
    font: '"Playfair Display", "Georgia", serif',
    text: '#F5F0E8',
    tagline: 'SOPHISTICATED WHITESPACE HIGH END',
    description: 'Editorial layouts with elegant serif fonts and quiet prestige gold accents',
    borderRadius: '24px',
    shadow: '0 12px 48px rgba(197,160,89,0.08)',
    titlePlacement: 'center',
    padding: '5rem',
    headerSize: '3.2rem',
    contentSize: '1.2rem',
    headerWeight: '300',
    backgroundGradient: 'radial-gradient(circle at center, #1a1a1a 0%, #111111 100%)',
    borderColor: '#2a2a2a',
    templateId: 'luxury_investor',
  },
  'Dark Investor': {
    primaryColor: '#020617',
    accentColor: '#FBBF24',
    font: '"Inter", sans-serif',
    text: '#CBD5E1',
    tagline: 'DARK PREMIUM VENTURE GRADE',
    description: 'Deep dark layout with amber accents — venture-grade investor presentation',
    borderRadius: '12px',
    shadow: '0 8px 32px rgba(251,191,36,0.1)',
    titlePlacement: 'left',
    padding: '3.5rem',
    headerSize: '3rem',
    contentSize: '1.2rem',
    headerWeight: '800',
    backgroundGradient: 'none',
    borderColor: '#1e293b',
    templateId: 'dark_investor',
  },
  'Bright Modern': {
    primaryColor: '#FFFFFF',
    accentColor: '#4F46E5',
    font: '"Inter", sans-serif',
    text: '#0F172A',
    tagline: 'CLEAN VIVID PRODUCT FOCUS',
    description: 'Bright modern layout with indigo accents — product and growth focused',
    borderRadius: '12px',
    shadow: '0 4px 20px rgba(79,70,229,0.08)',
    titlePlacement: 'left',
    padding: '3.5rem',
    headerSize: '2.8rem',
    contentSize: '1.1rem',
    headerWeight: '700',
    backgroundGradient: 'none',
    borderColor: '#e2e8f0',
    templateId: 'bright_modern',
  },
  'DecisionLab Signature': {
    primaryColor: '#08131D',
    accentColor: '#5DA9FF',
    font: '"Space Grotesk", "Inter", sans-serif',
    text: '#E8EDF5',
    tagline: 'DECISIONLAB CERTIFIED PRESENTATION',
    description: 'The official DecisionLab investor presentation — premium dark with cobalt',
    borderRadius: '16px',
    shadow: '0 8px 32px rgba(93,169,255,0.2)',
    titlePlacement: 'left',
    padding: '3.5rem',
    headerSize: '3.4rem',
    contentSize: '1.25rem',
    headerWeight: '900',
    backgroundGradient: 'radial-gradient(circle at top right, #0d2035, #08131D)',
    borderColor: '#1e2d3d',
    templateId: 'dl_signature',
  },
};